# Generated by Django 4.1 on 2023-10-12 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('admin_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 10, 12, 9, 56, 40, 954750, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('recipient', models.CharField(max_length=255)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.courier')),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.branchoffice')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('branch_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.branchoffice')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.parcel')),
            ],
        ),
        migrations.AddField(
            model_name='parcel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.user'),
        ),
        migrations.AddField(
            model_name='courier',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.station'),
        ),
    ]
