# Generated by Django 4.1 on 2023-10-12 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 9, 59, 18, 747814, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False),
        ),
    ]
