# Generated by Django 4.1 on 2023-10-14 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0003_alter_parcel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backstage.station'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backstage.courier'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='destination_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backstage.branchoffice'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='timestamp',
            field=models.BigIntegerField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backstage.user'),
        ),
        migrations.AlterField(
            model_name='station',
            name='branch_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backstage.branchoffice'),
        ),
    ]
