# Generated by Django 4.1 on 2023-10-14 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0004_alter_courier_station_alter_parcel_courier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.station'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.courier'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='destination_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.branchoffice'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.user'),
        ),
        migrations.AlterField(
            model_name='station',
            name='branch_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.branchoffice'),
        ),
    ]
