# Generated by Django 4.1 on 2023-10-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0005_alter_courier_station_alter_parcel_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='password',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courier',
            name='username',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
