# Generated by Django 4.1 on 2023-10-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0006_courier_password_courier_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='object_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
