# Generated by Django 4.1 on 2023-10-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0010_alter_parcel_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='Price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
