# Generated by Django 4.1 on 2023-10-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0011_parcel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='destination',
        ),
    ]
