# Generated by Django 4.1 on 2023-10-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0012_remove_parcel_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='timestamp',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
